### ISSUE TITLE
Bug grave

### ISSUE THREAD

**Issue by terminator-97** [Bay62/SCP-Mengacci#1]
Ogni tanto mentre uso questo plugin partono dei broadcast di tafazzi, non so cosa fare, ora nel server tutti si massacrano i coglioni con le bottiglie di plastica

**Comment by iopietro** [comment]
Buonasera,

Le posso assicurare che questo non sia un bug, ma un effetto collaterale del plugin.

Distinti saluti.

**Comment by Bay62** [comment]
Può essere, questa sera farò uscire il fix 1.0.3
@terminator-97

**Comment by Bay62** [comment]
@terminator-97 
https://github.com/Bay62/SCP-Mengacci/releases/tag/1.0.3
